additionalProperties:
  projectName: KindeSDK
  swiftPackagePath: Sources/KindeSDK/
  artifactId: swift-sdk-generator
  useAsyncAwait: true
  validatable: false

templateDir: template
files:
   APIHelper.mustache:
      destinationFilename: Sources/KindeSDK/Utils/APIHelper.swift
   Extensions.mustache:
      destinationFilename: Sources/KindeSDK/Utils/Extensions.swift
   CodableHelper.mustache:
      destinationFilename: Sources/KindeSDK/Utils/CodableHelper.swift
   JSONDataEncoding.mustache:
      destinationFilename: Sources/KindeSDK/Utils/JSONDataEncoding.swift
   JSONEncodingHelper.mustache: 
      destinationFilename: Sources/KindeSDK/Utils/JSONEncodingHelper.swift
   Models.mustache: 
      destinationFilename: Sources/KindeSDK/Utils/Models.swift
   OpenISO8601DateFormatter.mustache:
      destinationFilename: Sources/KindeSDK/Utils/OpenISO8601DateFormatter.swift
   URLSessionImplementations.mustache:
      destinationFilename: Sources/KindeSDK/Utils/URLSessionImplementations.swift

   Auth/Auth.swift: {
      destinationFilename: Sources/KindeSDK/Auth/Auth.swift
   }
   Auth/AuthError.swift: {
      destinationFilename: Sources/KindeSDK/Auth/AuthError.swift
   }
   Auth/AuthStateRepository.swift: {
      destinationFilename: Sources/KindeSDK/Auth/AuthStateRepository.swift
   }
   Auth/BearerDecodableRequestBuilder.swift: {
      destinationFilename: Sources/KindeSDK/Auth/BearerDecodableRequestBuilder.swift
   }
   Auth/BearerRequestBuilder.swift: {      
      destinationFilename: Sources/KindeSDK/Auth/BearerRequestBuilder.swift
   }
   Auth/BearerRequestBuilderFactory.swift: {
      destinationFilename: Sources/KindeSDK/Auth/BearerRequestBuilderFactory.swift
   }
   Auth/BearerTokenHandler.swift: {
      destinationFilename: Sources/KindeSDK/Auth/BearerTokenHandler.swift
   }
   Auth/Config.swift: {
      destinationFilename: Sources/KindeSDK/Auth/Config.swift
   }
   Auth/DefaultLogger.swift: {
      destinationFilename: Sources/KindeSDK/Auth/DefaultLogger.swift
   }
   Auth/Tokens.swift: {
      destinationFilename: Sources/KindeSDK/Auth/Tokens.swift
   }
   Auth/FlagError.swift: {
      destinationFilename: Sources/KindeSDK/Auth/FlagError.swift
   }
   
   Utils/AtomicWrapper.swift: {
      destinationFilename: Sources/KindeSDK/Utils/AtomicWrapper.swift
   }
   Utils/Keychain.swift: {
      destinationFilename: Sources/KindeSDK/Utils/Keychain.swift
   }
   Utils/String+JWTTokenDecode.swift: {
      destinationFilename: Sources/KindeSDK/Utils/String+JWTTokenDecode.swift
   }
   Utils/PList.swift: {
      destinationFilename: Sources/KindeSDK/Utils/PList.swift
   }
   Utils/SDKVersion.swift: {
      destinationFilename: Sources/KindeSDK/Utils/SDKVersion.swift
   }

   Tests/AuthErrorSpec.swift: {
      destinationFilename: Tests/AuthErrorSpec.swift
   }
   Tests/AuthSpec.swift: {
      destinationFilename: Tests/AuthSpec.swift
   }
   Tests/ConfigSpec.swift: {
      destinationFilename: Tests/ConfigSpec.swift
   }
   Tests/DefaultLoggerSpec.swift: {
      destinationFilename: Tests/DefaultLoggerSpec.swift
   }
   Tests/StringJWTTokenDecodeSpec.swift: {
      destinationFilename: Tests/StringJWTTokenDecodeSpec.swift
   }
   CustomFiles/README.md: {
      destinationFilename: README.md
   }
   CustomFiles/LICENSE: {
      destinationFilename: LICENSE
   }
   CustomFiles/Package.resolved: {
      destinationFilename: Package.resolved
   }
   CustomFiles/kinde-auth.json: {
      destinationFilename: kinde-auth.json
   }
   CustomFiles/KindeSDK-Info.plist: {
      destinationFilename: KindeSDK-Info.plist
   }
   CustomFiles/.gitignore: {
      destinationFilename: .gitignore
   }
