openapi: "3.0.0"
info:
  version: 0.0.1
  title: Kinde Management API
  description: Provides endpoints to manage your Kinde Businesses
  termsOfService: https://kinde.com/docs/looking-after-you/terms-of-service
  contact:
    name: Kinde Support Team
    email: support@kinde.com
    url: https://kinde.com/docs
servers:
  - url: https://{businessName}.kinde.com
    variables:
      businessName:
        description: Business Name created in the Kinde Console
        default: app
security:
  - kindeBearerAuth: [] 
tags:
  - name: Users
    description: Everything about your end-users
paths:
  /oauth2/v2/user_profile:
    get:
      tags:
        - OAuth
      operationId: getUser
      description: |
        Contains the id, names and email of the currently logged in user
      summary: Returns the details of the currently logged in user
      responses:
        '200':
          description: A succesful response with the user details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_profile'
        '403':
          description: Invalid credentials
components:
  schemas:
    user:
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: string
        email:
          type: string
        full_name:
          type: string
        last_name:
          type: string
        first_name:
          type: string
        is_suspended:
          type: boolean
    user_profile:
      type: object
      required:
        - id
        - updated_at
      properties:
        id:
          type: string
        provided_id:
          type: string
        name:
          type: string
        given_name:
          type: string
        family_name:
          type: string
        updated_at:
          type: integer
  securitySchemes:
    kindeBearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 
